version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
#   build:
#     docker:
#       - image: cimg/node:18.12
#     steps:
#       - run:
#          name: production build
#          command: npm run webpack:production
#       - persist_to_workspace:
#           root: ./dist
#           paths:
#             - .

  netlify-deploy:
    docker:
      - image: cimg/node:18.12
    steps:
      - attach_workspace:
         at: ./dist
      - run:
         name: install netlify command globally
         command: npm i netlify-cli
      - run:
         name: deploy to netlify
         working_directory: ~/project
         command: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist

workflows:
  test-build-deploy:
    jobs:
      - node/test:
         version: '18.12'
      - node/run:
         version: '18.12'
         npm-run: webpack:production
         post-steps:
          - run:
              command: ls -la
          - persist_to_workspace:
              root: ./dist
              paths:
                - .
      - deploy-approval:
         type: approval
         filters:
          branches:
            only:
              - master
         requires:
           - node/test
           - node/run
      - netlify-deploy:
         filters:
          branches:
            only:
              - master
         requires:
           - deploy-approval
