version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  # Netlifyへデプロイ
  netlify-deploy:
    docker:
      - image: cimg/node:18.12
    steps:
      # 事前のビルドステップから成果物を受け取る
      - attach_workspace:
         at: ./dist
      # netlify-cliをあらかじめインストールしているとnpm ciがEBADPLATFORMで失敗する（ローカル、CI関係なく）
      # 原因が今現在は不明なため、ワークアラウンドとしてデプロイフローにnetlify-cliを追加でインストールすることでこれを回避している
      - run:
         name: install netlify command
         command: npm i netlify-cli
      # デプロイ実行
      - run:
         name: deploy to netlify
         working_directory: ~/project
         command: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist

workflows:
  test-build-deploy:
    jobs:
      # ユニットテスト実行
      - node/test:
         version: '18.12'
      # プロダクションビルド実行（成果物はデプロイジョブで参照できるように永続化） 
      - node/run:
         version: '18.12'
         npm-run: webpack:production
         post-steps:
          - persist_to_workspace:
              root: ./dist
              paths:
                - .
      # デプロイを実行するか否かを手動でCircleCI上で確認させるステップ（restrict contextで誰ができるかも指定可能）
      - deploy-approval:
         type: approval
         filters:
          branches:
            only:
              - master
         requires:
           - node/test
           - node/run
      # デプロイがapproveされたら実行される
      - netlify-deploy:
         filters:
          branches:
            only:
              - master
         requires:
           - deploy-approval
